### ISSUE TITLE
Deeper level to more refine infographs within a bubble

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#376] opened 2019-11-25 19:41 UTC
For example, after selecting `Finances` bubble, have some sort of a filter (like show only transfer payments panels, or FTE panels, etc.)

![Screen Shot 2019-11-25 at 2 40 30 PM](https://user-images.githubusercontent.com/29746626/69572192-9dc79a00-0f91-11ea-9730-279d01b05e3f.png)
Suggestion from Infobase Heuristic Report

**Comment by ktw1016** [comment] 2020-01-22 18:17
We know what tables for each panel so we can filter depending on what data each panel contains.
Problems with that:
1. Budget not tabled
2. Key concepts, empty table (this isn't actually a problem)

**Comment by ktw1016** [comment] 2020-03-02 14:32
I think #529 should have closed it. Reopen if needed

**Comment by ktw1016** [comment] 2020-11-27 15:41
This should never have closed actually

**Comment by Stephen-ONeil** [comment] 2021-04-19 20:04
Duplicate of #642

**Closed by Stephen-ONeil** 2021-04-19 20:04 UTC
Labels: enhancement, project, user testing
