### ISSUE TITLE
Multiple bugs in revenue-heavy (revenue-only?) program infographics

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#360] opened 2019-11-15 16:09 UTC
e.g. https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/program/AGR-AAB00/infograph/financial

**Comment by ktw1016** [comment] 2020-01-15 16:24
What are the multiple bugs in this?

**Comment by Stephen-ONeil** [comment] 2020-04-06 21:12
Duplicate of #341 (? maybe, otherwise I don't know what it's about, may have been the state of this infographic under old data?)

**Closed by Stephen-ONeil** 2020-04-06 21:12 UTC
Labels: bug
